// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.testprint.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DosaIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DosaIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DosaIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DosaIntegrationTest: @Transactional;
    
    @Autowired
    private DosaDataOnDemand DosaIntegrationTest.dod;
    
    @Test
    public void DosaIntegrationTest.testCountDosas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", dod.getRandomDosa());
        long count = com.springsource.roo.testprint.domain.Dosa.countDosas();
        org.junit.Assert.assertTrue("Counter for 'Dosa' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DosaIntegrationTest.testFindDosa() {
        com.springsource.roo.testprint.domain.Dosa obj = dod.getRandomDosa();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to provide an identifier", id);
        obj = com.springsource.roo.testprint.domain.Dosa.findDosa(id);
        org.junit.Assert.assertNotNull("Find method for 'Dosa' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Dosa' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DosaIntegrationTest.testFindAllDosas() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", dod.getRandomDosa());
        long count = com.springsource.roo.testprint.domain.Dosa.countDosas();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Dosa', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.springsource.roo.testprint.domain.Dosa> result = com.springsource.roo.testprint.domain.Dosa.findAllDosas();
        org.junit.Assert.assertNotNull("Find all method for 'Dosa' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Dosa' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DosaIntegrationTest.testFindDosaEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", dod.getRandomDosa());
        long count = com.springsource.roo.testprint.domain.Dosa.countDosas();
        if (count > 20) count = 20;
        java.util.List<com.springsource.roo.testprint.domain.Dosa> result = com.springsource.roo.testprint.domain.Dosa.findDosaEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Dosa' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Dosa' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DosaIntegrationTest.testFlush() {
        com.springsource.roo.testprint.domain.Dosa obj = dod.getRandomDosa();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to provide an identifier", id);
        obj = com.springsource.roo.testprint.domain.Dosa.findDosa(id);
        org.junit.Assert.assertNotNull("Find method for 'Dosa' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDosa(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Dosa' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DosaIntegrationTest.testMerge() {
        com.springsource.roo.testprint.domain.Dosa obj = dod.getRandomDosa();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to provide an identifier", id);
        obj = com.springsource.roo.testprint.domain.Dosa.findDosa(id);
        boolean modified =  dod.modifyDosa(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.springsource.roo.testprint.domain.Dosa merged = (com.springsource.roo.testprint.domain.Dosa) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Dosa' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DosaIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", dod.getRandomDosa());
        com.springsource.roo.testprint.domain.Dosa obj = dod.getNewTransientDosa(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Dosa' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Dosa' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DosaIntegrationTest.testRemove() {
        com.springsource.roo.testprint.domain.Dosa obj = dod.getRandomDosa();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Dosa' failed to provide an identifier", id);
        obj = com.springsource.roo.testprint.domain.Dosa.findDosa(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Dosa' with identifier '" + id + "'", com.springsource.roo.testprint.domain.Dosa.findDosa(id));
    }
    
}
