// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.springsource.roo.testprint.domain;


privileged aspect Dosa_Roo_ToString {
    
    public String Dosa.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Price: ").append(getPrice());
        return sb.toString();
    }
    
}
